"use client";

import React from "react";

const languages = [
  "English",
  "Spanish",
  "French",
  "German",
  "Chinese (Simplified)",
  "Chinese (Traditional)",
  "Japanese",
  "Korean",
  "Hindi",
  "Arabic",
  "Portuguese (Portugal)",
  "Portuguese (Brazil)",
  "Russian",
  "Italian",
  "Dutch",
  "Turkish",
  "Polish",
  "Ukrainian",
  "Romanian",
  "Greek",
  "Czech",
  "Hungarian",
  "Swedish",
  "Finnish",
  "Norwegian",
  "Danish",
  "Hebrew",
  "Thai",
  "Vietnamese",
  "Indonesian",
  "Malay",
  "Filipino",
  "Bengali",
  "Punjabi (Gurmukhi)",
  "Punjabi (Shahmukhi)",
  "Tamil",
  "Telugu",
  "Marathi",
  "Gujarati",
  "Kannada",
  "Malayalam",
  "Urdu",
  "Persian (Farsi)",
  "Pashto",
  "Swahili",
  "Zulu",
  "Xhosa",
  "Afrikaans",
  "Amharic",
  "Somali",
  "Hausa",
  "Igbo",
  "Yoruba",
  "Maori",
  "Samoan",
  "Tongan",
  "Fijian",
  "Haitian Creole",
  "Javanese",
  "Sundanese",
  "Burmese (Myanmar)",
  "Khmer",
  "Lao",
  "Nepali",
  "Sinhala",
  "Mongolian",
  "Kazakh",
  "Uzbek",
  "Tajik",
  "Kyrgyz",
  "Armenian",
  "Georgian",
  "Azerbaijani",
  "Basque",
  "Catalan",
  "Galician",
  "Welsh",
  "Irish",
  "Scottish Gaelic",
  "Breton",
  "Corsican",
  "Luxembourgish",
  "Icelandic",
  "Estonian",
  "Latvian",
  "Lithuanian",
  "Slovak",
  "Slovenian",
  "Croatian",
  "Serbian",
  "Bosnian",
  "Macedonian",
  "Albanian",
  "Bulgarian",
  "Belarusian",
  "Malay (Brunei)",
  "Chichewa",
  "Esperanto",
  "Frisian",
  "Latin",
];

export default function LanguageSelect() {
  return (
    <select className="w-full p-2 mt-1 border rounded">
      {languages.map((lang) => (
        <option key={lang}>{lang}</option>
      ))}
    </select>
  );
}
